punya inggrid# Ini didukung platform model pendanaan
inggrid06
github                            :                              # Ganti dengan 4 GitHub Sponsor yang diaktifkan nama pengguna misalnya, [user1, user2]
patreon                            :                              # Ganti dengan satu nama pengguna Patreon
open_collective                            :                              # Ganti dengan satu nama pengguna Open Collective
ko_fi                           :                             # Ganti dengan satu nama pengguna Ko-fi tunggal
tidelift                           :                             # Ganti dengan satu nama platform Tidelift/nama paket-nama misalnya, npm/babel
community_bridge                           :                             # Ganti dengan satu nama proyek Jembatan Community misalnya, cloud-foundry
liberapay                           :                             # Ganti dengan satu nama pengguna Liberapay
issuehunt                           :                             # Ganti dengan satu nama pengguna IssueHunt
otechie                           :                             # Ganti dengan satu nama pengguna Otechie
lfx_crowdfunding                           :                             # Ganti dengan satu nama proyek LFX Crowdfunding misalnya, cloud-foundry
kebiasaan                           :                            # Ganti dengan hingga 4 URL sponsorship kustom misalnya, ['link1', 'link2']
